### ISSUE TITLE
AI聊天好像没有过滤消息富文本

### ISSUE THREAD

**Issue by redpandaex** [zsdddz/AQChat#1]
![image](https://github.com/zsdddz/AQChat/assets/95856798/2f738130-4a93-454f-a5c5-825b7dbfcfbf)

**Comment by WoodrowLytton** [comment]
我们也发现了这个情况，已经加入开发计划，会在下版本处理

**Comment by zsdddz** [comment]
我们也发现了这个问题，已经加入开发计划，会在下次更新时处理

**Comment by zsdddz** [comment]
已经更新解析md

**Comment by elarbor** [comment]
对应的后端仓库在哪啊？

**Comment by zsdddz** [comment]
> 对应的后端仓库在哪啊？

主页或者文档都有 https://github.com/zsdddz/AQChatServer
