### ISSUE TITLE
看起来富文本输入框貌似会执行XSS

### ISSUE THREAD

**Issue by redpandaex** [zsdddz/AQChat#2]
`<img src=x oneRRoR="alert(&quot;is xss&quot;)">`
![image](https://github.com/zsdddz/AQChat/assets/95856798/76bc8fd0-aeca-45a5-a36d-7ed835239883)

**Comment by zsdddz** [comment]
感谢，马上处理这个问题

**Comment by zsdddz** [comment]
已处理，预计凌晨更新演示环境
